"""Even Fibonacci numbers
Problem statement:

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

"""


def fibo(limit):
    f = [1, 2]
    while f[len(f) - 1] + f[len(f) - 2] < limit:
        f.append(f[len(f) - 1] + f[len(f) - 2])
    return f


def main():
    print(sum(x for x in fibo(4000000) if x % 2 == 0))


if __name__ == "__main__":
    main()
